import 'package:flutter/material.dart';
import 'package:gamescoop/models.dart';

List<AssetImage> ValorantImages = [
  const AssetImage("asset/Valorant/Agents/Astra.png"),
  const AssetImage("asset/Valorant/Agents/Breach.png"),
  const AssetImage("asset/Valorant/Agents/Brimestone.png"),
  const AssetImage("asset/Valorant/Agents/Chamber.png"),
  const AssetImage("asset/Valorant/Agents/Cypher.png"),
  const AssetImage("asset/Valorant/Agents/Fade.png"),
  const AssetImage("asset/Valorant/Agents/Jett.png"),
  const AssetImage("asset/Valorant/Agents/Kayo.png"),
  const AssetImage("asset/Valorant/Agents/Killjoy.png"),
  const AssetImage("asset/Valorant/Agents/Neon.png"),
  const AssetImage("asset/Valorant/Agents/Omen.png"),
  const AssetImage("asset/Valorant/Agents/Pheonix.png"),
  const AssetImage("asset/Valorant/Agents/Raze.png"),
  const AssetImage("asset/Valorant/Agents/Reyna.png"),
  const AssetImage("asset/Valorant/Agents/Sage.png"),
  const AssetImage("asset/Valorant/Agents/Skye.png"),
  const AssetImage("asset/Valorant/Agents/Sova.png"),
  const AssetImage("asset/Valorant/Agents/Viper.png"),
  const AssetImage("asset/Valorant/Agents/Yoru.png"),
];
List<String> ValorantAgentImages = [
  "asset/Valorant/Agents/Astra.png",
  "asset/Valorant/Agents/Breach.png",
  "asset/Valorant/Agents/Brimestone.png",
  "asset/Valorant/Agents/Chamber.png",
  "asset/Valorant/Agents/Cypher.png",
  "asset/Valorant/Agents/Fade.png",
  "asset/Valorant/Agents/Jett.png",
  "asset/Valorant/Agents/Kayo.png",
  "asset/Valorant/Agents/Killjoy.png",
  "asset/Valorant/Agents/Neon.png",
  "asset/Valorant/Agents/Omen.png",
  "asset/Valorant/Agents/Pheonix.png",
  "asset/Valorant/Agents/Raze.png",
  "asset/Valorant/Agents/Reyna.png",
  "asset/Valorant/Agents/Sage.png",
  "asset/Valorant/Agents/Skye.png",
  "asset/Valorant/Agents/Sova.png",
  "asset/Valorant/Agents/Viper.png",
  "asset/Valorant/Agents/Yoru.png",
];

List<String> AgentName = [
  "Astra",
  "Breach",
  "Brimestone",
  "Chamber",
  "Cypher",
  "Fade",
  "Jett",
  "Kay/O",
  "Killjoy",
  "Neon",
  "Omen",
  "Pheonix",
  "Raze",
  "Reyna",
  "Sage",
  "Skye",
  "Sova",
  "Viper",
  "Yoru",
];
List<String> MapsImages = [
  "asset/Valorant/Maps/Ascent.webp",
  "asset/Valorant/Maps/Bind.webp",
  "asset/Valorant/Maps/Breeze.webp",
  "asset/Valorant/Maps/Fracture.webp",
  "asset/Valorant/Maps/Haven.webp",
  "asset/Valorant/Maps/Icebox.webp",
  "asset/Valorant/Maps/Range.webp",
  "asset/Valorant/Maps/Split.webp",
];

List<String> MapName = [
  "Ascent",
  "Bind",
  "Breeze",
  "Fracture",
  "Haven",
  "Ice-Box",
  "Range",
  "Split",
];

List<AssetImage> FeatureImages = [
  const AssetImage("asset/Valorant/Duelist.png"),
  const AssetImage("asset/Valorant/Initiater.png"),
  const AssetImage("asset/Valorant/Sentiniel.png"),
  const AssetImage("asset/Valorant/Controller.png"),
];
List<Color> CardColor = [
  Colors.pink.shade700,
  Colors.green.shade700,
  Colors.brown.shade700,
  Colors.grey.shade700,
  Colors.white,
  Colors.cyan.shade700,
  Colors.lightBlue.shade700,
  Colors.yellow.shade700,
  Colors.deepPurpleAccent.shade700,
  Colors.blue.shade700,
  Colors.orange.shade700,
  Colors.blueGrey.shade700,
  Colors.purple.shade700,
  Colors.greenAccent.shade700,
  Colors.redAccent.shade700,
  Colors.blue.shade700,
  Colors.green.shade900,
  Colors.blueAccent.shade700,
  Colors.blueAccent.shade700,
];
List<String> AvatarRoles = [
  "Duelist",
  "Initiater",
  "Sentinel",
  "Controller",
];
List<String> AgentDescription = [
  '"Ghanaian Agent Astra harnesses the energies of the cosmos to reshape battlefields to her whim. With full command of her astral form and a talent for deep strategic foresight, she’s always eons ahead of her enemy’s next move."',
  '"Breach, the bionic Swede, fires powerful, targeted kinetic blasts to aggressively clear a path through enemy ground. The damage and disruption he inflicts ensures no fight is ever fair."',
  '"Joining from the USA, Brimstones orbital arsenal ensures his squad always has the advantage. His ability to deliver utility precisely and from a distance make him an unmatched boots-on-the-ground commander."',
  '"Well dressed and well armed, French weapons designer Chamber expels aggressors with deadly precision. He leverages his custom arsenal to hold the line and pick off enemies from afar, with a contingency built for every plan."',
  '"The Moroccan information broker, Cypher is a one-man surveillance network who keeps tabs on the enemy’s every move. No secret is safe. No maneuver goes unseen. Cypher is always watching."',
  '"Turkish bounty hunter Fade unleashes the power of raw nightmare to seize enemy secrets. Attuned with terror itself, she hunts down targets and reveals their deepest fears - before crushing them in the dark."',
  '"Representing her home country of South Korea, Jetts agile and evasive fighting style lets her take risks no one else can. She runs circles around every skirmish, cutting enemies before they even know what hit them."',
  '"KAY/O is a machine of war built for a single purpose: neutralizing radiants. His power to suppress enemy abilities cripples his opponents capacity to fight back, securing him and his allies the ultimate edge."',
  '"The genius of Germany, Killjoy secures the battlefield with ease using her arsenal of inventions. If the damage from her gear does not stop her enemies, her robots debuff will help make short work of them."',
  '"Filipino Agent, Neon, surges forward at shocking speeds, discharging bursts of bioelectric radiance as fast as her body generates it. She races ahead to catch enemies off guard, then strikes them down quicker than lightning."',
  '"A phantom of a memory, Omen hunts in the shadows. He renders enemies blind, teleports across the field, then lets paranoia take hold as his foe scrambles to learn where he might strike next."',
  '"Hailing from the U.K., Phoenix is star power shines through in his fighting style, igniting the battlefield with flash and flare. Whether he got backup or not, he will rush into a fight on his own terms."',
  '"Raze explodes out of Brazil with her big personality and big guns. With her blunt-force-trauma playstyle, she excels at flushing entrenched enemies and clearing tight spaces with a generous dose of “boom.”"',
  '"Forged in the heart of Mexico, Reyna dominates single combat, popping off with each kill she scores. Her capability is only limited by her raw skill, making her highly dependent on performance."',
  '"The bastion of China, Sage creates safety for herself and her team wherever she goes. Able to revive fallen friends and stave off aggressive pushes, she provides a calm center to a hellish fight."',
  '"Hailing from Australia, Skye and her band of beasts trail-blaze the way through hostile territory. With her creations hampering the enemy, and her power to heal others, the team is strongest and safest by Skyes side."',
  '"Born from the eternal winter of Russias tundra, Sova tracks, finds, and eliminates enemies with ruthless efficiency and precision. His custom bow and incredible scouting abilities ensure that even if you run, you cannot hide."',
  '"The American chemist, Viper deploys an array of poisonous chemical devices to control the battlefield and cripple the enemys vision. If the toxins do not kill her prey, her mind games surely will."',
  '"Japanese native Yoru rips holes straight through reality to infiltrate enemy lines unseen. Using deception and aggression in equal measure, he gets the drop on each target before they know where to look."',
];
